create table if not exists public.promotion_popup_questions (
  id bigint generated by default as identity primary key,
  promotion_id bigint not null references public.promotion_popup(id) on delete cascade,
  field_key text not null,
  question text not null,
  input_type text not null default 'text' check (input_type in ('text', 'email', 'phone', 'number')),
  validation_pattern text,
  validation_message text,
  is_required boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (promotion_id, field_key)
);

create table if not exists public.promotion_popup_responses (
  id bigint generated by default as identity primary key,
  promotion_id bigint not null references public.promotion_popup(id) on delete cascade,
  email text,
  answers jsonb not null default '{}'::jsonb,
  coupon_revealed boolean not null default false,
  revealed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists promotion_popup_questions_order_idx on public.promotion_popup_questions (promotion_id, is_active, sort_order);
create index if not exists promotion_popup_responses_promotion_idx on public.promotion_popup_responses (promotion_id, created_at desc);

alter table public.promotion_popup_questions enable row level security;
alter table public.promotion_popup_responses enable row level security;

drop policy if exists "Public can view active promotion questions" on public.promotion_popup_questions;
create policy "Public can view active promotion questions" on public.promotion_popup_questions
for select to anon, authenticated
using (is_active = true and exists (select 1 from public.promotion_popup p where p.id = promotion_popup_questions.promotion_id and p.is_active = true));

drop policy if exists "Public can submit promotion responses" on public.promotion_popup_responses;
create policy "Public can submit promotion responses" on public.promotion_popup_responses
for insert to anon, authenticated
with check (exists (select 1 from public.promotion_popup p where p.id = promotion_popup_responses.promotion_id and p.is_active = true));

create or replace function public.set_promotion_popup_questions_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists promotion_popup_questions_updated_at on public.promotion_popup_questions;
create trigger promotion_popup_questions_updated_at before update on public.promotion_popup_questions
for each row execute function public.set_promotion_popup_questions_updated_at();