begin;

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  created_at timestamptz not null default now()
);

create index if not exists order_status_history_order_created_idx
  on public.order_status_history(order_id, created_at asc);

create or replace function public.record_order_status_history()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.order_status_history (order_id, status)
    values (new.id, coalesce(nullif(trim(new.status), ''), 'pending'));
  end if;
  return new;
end;
$$;

drop trigger if exists orders_record_status_history on public.orders;
create trigger orders_record_status_history
  after insert or update of status on public.orders
  for each row execute function public.record_order_status_history();

-- Make current orders visible in their timeline without changing the order.
insert into public.order_status_history (order_id, status, created_at)
select id, coalesce(nullif(trim(status), ''), 'pending'), created_at
from public.orders
where not exists (
  select 1 from public.order_status_history history where history.order_id = orders.id
);

alter table public.order_status_history enable row level security;
revoke all on table public.order_status_history from public, anon, authenticated;
grant select, insert on table public.order_status_history to service_role;

commit;
